version: "3"

services:
  graphql:
    build:
      context: ./dictionary-graphql
      dockerfile: Dockerfile
      target: dev
    command: air -c .air.toml
    depends_on:
      - db
    hostname: graphql
    volumes:
      - ./dictionary-graphql:/app
      - ./schema.graphql:/schema.graphql
    ports:
      - 8080:8080
    restart: always
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 27017
      DB_NAME: dictionary_go_nuxt_graphql
      TEST_DB_NAME: dictionary_go_nuxt_graphql_test
      ALLOW_ORIGINS: '["http://localhost:3000"]'
  db:
    build:
      context: ./
      dockerfile: db.Dockerfile
    hostname: db
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  application-ui:
    build: 
      context: ./dictionary-application-ui
      dockerfile: Dockerfile
      target: dev
      args:
        - HTTP_ENDPOINT=http://graphql:8080/graphql
        - BROWSER_HTTP_ENDPOINT=http://localhost:8080/graphql
    command: yarn dev
    depends_on:
      - graphql
    hostname: application-ui
    volumes:
      - ./dictionary-application-ui:/app
      - application_ui_node_modules:/app/node_modules
      - ./schema.graphql:/schema.graphql
    ports:
      - 3000:3000

volumes:
  application_ui_node_modules:
  db_data:
  db_config:
