#!/usr/bin/env bash

set -eu

cd "$(dirname "$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd)")"

(cd dictionary-application-ui && rm -rf node_modules node_modules_tmp)

docker-compose build application-ui

./scripts/attach-application-ui <<EOL
yarn
tar zcvf node_modules_tmp node_modules > /dev/null
EOL

cd dictionary-application-ui

tar zxvf node_modules_tmp > /dev/null
rm -rf node_modules_tmp
