// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Characteristic struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Description struct {
	Text   string `json:"text"`
	Series string `json:"Series"`
}

type Gender struct {
	Name     string `json:"name"`
	IconName string `json:"iconName"`
}

type Pokemon struct {
	NationalNo      int               `json:"nationalNo"`
	Name            string            `json:"name"`
	ImageName       string            `json:"imageName"`
	Species         string            `json:"species"`
	Height          string            `json:"height"`
	Weight          string            `json:"weight"`
	Genders         []*Gender         `json:"genders"`
	Types           []*Type           `json:"types"`
	Characteristics []*Characteristic `json:"characteristics"`
	Description     *Description      `json:"description"`
}

type Type struct {
	Name     string `json:"name"`
	IconName string `json:"iconName"`
}
