// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Gender struct {
	Name     string `json:"name"`
	IconName string `json:"iconName"`
}

type Pokemon struct {
	NationalNo int       `json:"nationalNo"`
	Name       string    `json:"name"`
	ImageName  string    `json:"imageName"`
	Genders    []*Gender `json:"genders"`
}
