// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PokemonResult interface {
	IsPokemonResult()
}

type Ability struct {
	Heart          int `json:"heart"`
	Attack         int `json:"attack"`
	Defense        int `json:"defense"`
	SpecialAttack  int `json:"specialAttack"`
	SpecialDefense int `json:"specialDefense"`
	Speed          int `json:"speed"`
}

type Characteristic struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Description struct {
	Text   string `json:"text"`
	Series string `json:"series"`
}

type Gender struct {
	Name    string `json:"name"`
	IconURL string `json:"iconURL"`
}

type LinkInfo struct {
	PrevID  int  `json:"prevId"`
	NextID  int  `json:"nextId"`
	HasPrev bool `json:"hasPrev"`
	HasNext bool `json:"hasNext"`
}

type Pokemon struct {
	ID              int               `json:"id"`
	NationalNo      int               `json:"nationalNo"`
	Name            string            `json:"name"`
	ImageURL        string            `json:"imageURL"`
	Species         string            `json:"species"`
	Height          string            `json:"height"`
	Weight          string            `json:"weight"`
	Genders         []*Gender         `json:"genders"`
	Types           []*Type           `json:"types"`
	Characteristics []*Characteristic `json:"characteristics"`
	Description     *Description      `json:"description"`
	Ability         *Ability          `json:"ability"`
	CanEvolution    bool              `json:"canEvolution"`
	Evolutions      []*Pokemon        `json:"evolutions"`
	LinkInfo        *LinkInfo         `json:"linkInfo"`
}

func (Pokemon) IsPokemonResult() {}

type PokemonNotFound struct {
	Message string `json:"message"`
}

func (PokemonNotFound) IsPokemonResult() {}

type Type struct {
	Name    string `json:"name"`
	IconURL string `json:"iconURL"`
}
